name: restified
description: ORM Rest API for Flutter
version: 0.0.18
homepage: https://github.com/caviezel/restified

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0
  shared_preferences: ^0.5.6+1      

dev_dependencies:
  flutter_test:
    sdk: flutter
